2023-04-29 11:11:53,211 INFO    ======================================================================
2023-04-29 11:11:53,211 INFO    Survey 286, for Ouro Preto, Minas Gerais
2023-04-29 11:11:53,212 INFO    Searching by bounding box, max_zoom=24
2023-04-29 11:11:53,213 INFO    ----------------------------------------------------------------------
2023-04-29 11:11:53,214 INFO    Rectangle calculated: [-20.2519, -43.4372, -20.5229, -43.7846]
2023-04-29 11:11:53,214 INFO    Searching rectangle: zoom factor = 0, node = []
2023-04-29 11:11:55,904 ERROR   Exception in get_search_page_info_rectangle
Traceback (most recent call last):
  File "C:\mono\airbnb-data-collection\airbnb_listing.py", line 161, in save
    self.__insert()
  File "C:\mono\airbnb-data-collection\airbnb_listing.py", line 236, in __insert
    cur.execute(sql, insert_args)
psycopg2.errors.UndefinedColumn: column "location_id" of relation "room" does not exist
LINE 10: ...    is_superhost, max_nights, pictures, bathroom, location_i...
                                                              ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\mono\airbnb-data-collection\airbnb_survey.py", line 809, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\mono\airbnb-data-collection\airbnb_listing.py", line 171, in save
    self.config.connection.conn.rollback()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'psycopg2.extensions.connection' object has no attribute 'conn'
2023-04-29 11:11:55,918 ERROR   Error in recurse_quadtree
Traceback (most recent call last):
  File "C:\mono\airbnb-data-collection\airbnb_listing.py", line 161, in save
    self.__insert()
  File "C:\mono\airbnb-data-collection\airbnb_listing.py", line 236, in __insert
    cur.execute(sql, insert_args)
psycopg2.errors.UndefinedColumn: column "location_id" of relation "room" does not exist
LINE 10: ...    is_superhost, max_nights, pictures, bathroom, location_i...
                                                              ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\mono\airbnb-data-collection\airbnb_survey.py", line 525, in recurse_quadtree
    (zoomable, median_leaf) = self.search_node(
                              ^^^^^^^^^^^^^^^^^
  File "C:\mono\airbnb-data-collection\airbnb_survey.py", line 809, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\mono\airbnb-data-collection\airbnb_listing.py", line 171, in save
    self.config.connection.conn.rollback()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'psycopg2.extensions.connection' object has no attribute 'conn'
2023-04-29 11:11:55,925 ERROR   Error
Traceback (most recent call last):
  File "C:\mono\airbnb-data-collection\airbnb_listing.py", line 161, in save
    self.__insert()
  File "C:\mono\airbnb-data-collection\airbnb_listing.py", line 236, in __insert
    cur.execute(sql, insert_args)
psycopg2.errors.UndefinedColumn: column "location_id" of relation "room" does not exist
LINE 10: ...    is_superhost, max_nights, pictures, bathroom, location_i...
                                                              ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\mono\airbnb-data-collection\airbnb_survey.py", line 463, in search
    self.recurse_quadtree(quadtree_node, median_node, None, flag)
  File "C:\mono\airbnb-data-collection\airbnb_survey.py", line 525, in recurse_quadtree
    (zoomable, median_leaf) = self.search_node(
                              ^^^^^^^^^^^^^^^^^
  File "C:\mono\airbnb-data-collection\airbnb_survey.py", line 809, in search_node
    if listing.save(self.config.FLAGS_INSERT_NO_REPLACE):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\mono\airbnb-data-collection\airbnb_listing.py", line 171, in save
    self.config.connection.conn.rollback()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'psycopg2.extensions.connection' object has no attribute 'conn'
2023-04-29 11:11:55,930 INFO    Selecting coordinates list from Airbnb
2023-04-29 11:11:55,933 INFO    Selecting sublocalities from city
2023-04-29 11:11:55,935 INFO    Selecting routes from sublocality
